apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
dryRun: false
nodeRegistration:
  kubeletExtraArgs:
    - name: node-ip
      value: "<NODE_IP>"
  criSocket: "unix:///var/run/containerd/containerd.sock"
  imagePullPolicy: "IfNotPresent"
  imagePullSerial: true
discovery:
  bootstrapToken:
    apiServerEndpoint: "<CONTROL_PLANE_NODE_IP>:6443"
    token: "<BOOTSTRAP_TOKEN>"
    unsafeSkipCAVerification: true
    caCertHashes:
      - "sha256:<CA_CERT_HASH>"
  tlsBootstrapToken: "<BOOTSTRAP_TOKEN>"
caCertPath: /etc/kubernetes/pki/ca.crt
# --- Uncomment this section only for control plane node joining ---
# controlPlane:
#   localAPIEndpoint:
#     advertiseAddress: "<NODE_IP>"
#     bindPort: 6443
#   certificateKey: "<CERTIFICATE_KEY>"
